### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by jcsuf**

### CODE REVIEW

**Comment by jcsuf** [comment]
?

**Comment by MineCreeper86** [comment]
> ?

？

**Comment by MineCreeper86** [comment]
@jcsuf Please DON'T make any changes on *.html file.
You can use `body{}` in style.css instead of using `.bgd`.
And MAKE SURE that there is NO conflict between two themes by using `root[theme="bing"]`.

**Comment by MineCreeper86** [comment]
I won't accept this Pull Request till no .html change appears.

**Review by MineCreeper86 — CHANGES_REQUESTED** [review]
.

**Pull request closed without merging**
